# Generated by Django 2.2 on 2019-04-09 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='known_subject',
            name='gpa',
            field=models.FloatField(null=True, validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='known_subject',
            name='specialty',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
