# Generated by Django 2.2 on 2019-04-08 20:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete='CASCADE', related_name='Profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
