# Generated by Django 2.2 on 2019-04-13 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutor_verification',
            name='verification',
        ),
        migrations.AddField(
            model_name='tutor_verification',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='tutor_verification',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='verification'),
        ),
    ]
