# Generated by Django 2.2 on 2019-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190409_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependent',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='known_subject',
            name='knowledge_level',
            field=models.CharField(choices=[('basic', 'Basic'), ('int', 'Intermediate'), ('adv', 'Advanced'), ('exp', 'Expert'), ('god', 'God')], max_length=50),
        ),
    ]
