# Generated by Django 2.2 on 2019-04-09 17:21

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('description', models.CharField(max_length=250)),
                ('booking_type', models.CharField(max_length=10)),
                ('pref_platform', models.CharField(max_length=50)),
                ('created_by', models.ForeignKey(null=True, on_delete='CASCADE', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'student_flag': True}, null=True, on_delete='CASCADE', related_name='student_book', to='accounts.Profile', to_field='user')),
                ('tutor', models.ForeignKey(limit_choices_to={'tutor_flag': True}, null=True, on_delete='CASCADE', related_name='tutor_book', to='accounts.Profile', to_field='user')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_Message_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('booking_id', models.OneToOneField(on_delete='CASCADE', to='bookings.Booking')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=6)),
                ('is_private', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Desired_Meeting_Place',
            fields=[
                ('meeting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookings.Meeting')),
            ],
            bases=('bookings.meeting',),
        ),
        migrations.CreateModel(
            name='Scheduled_Booking',
            fields=[
                ('booking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookings.Booking')),
            ],
            bases=('bookings.booking',),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(5)])),
                ('knowledge', models.CharField(max_length=100)),
                ('explanation', models.CharField(max_length=250)),
                ('invoice_id', models.OneToOneField(on_delete='CASCADE', to='bookings.Invoice')),
                ('reviewee', models.OneToOneField(on_delete='CASCADE', related_name='reviewee', to='accounts.Profile')),
                ('reviewer', models.OneToOneField(on_delete='CASCADE', related_name='reviewer', to='accounts.Profile')),
            ],
        ),
    ]
