# Generated by Django 2.1.7 on 2019-04-12 07:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20190412_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(help_text='YYYY-MM-DD hh:mm')),
                ('end_time', models.DateTimeField(help_text='YYYY-MM-DD hh:mm')),
                ('description', models.CharField(max_length=250)),
                ('pref_platform', models.CharField(choices=[('Online', 'Online'), ('In-Person', 'In-Person')], max_length=50)),
                ('transaction_time', models.DateTimeField(default=0)),
                ('hours', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Booking_Message_Logs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Booking_Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_Place',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('number', models.IntegerField()),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=6)),
                ('is_private', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('overall_rating', models.IntegerField(validators=[django.core.validators.MaxValueValidator(0), django.core.validators.MinValueValidator(5)])),
                ('explanation', models.CharField(max_length=250)),
                ('invoice_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='bookings.Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Desired_Meeting_Place',
            fields=[
                ('meeting_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookings.Meeting')),
            ],
            bases=('bookings.meeting',),
        ),
        migrations.CreateModel(
            name='Scheduled_Booking',
            fields=[
                ('booking_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='bookings.Booking')),
            ],
            bases=('bookings.booking',),
        ),
        migrations.AddField(
            model_name='invoice',
            name='booking',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Booking'),
        ),
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bookings.Meeting_Place', to_field='name'),
        ),
        migrations.AddField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(limit_choices_to={'student_flag': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_book', to='accounts.Profile', to_field='user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'tutor_flag': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_book', to='accounts.Profile', to_field='user'),
        ),
    ]
