# Generated by Django 2.2 on 2019-04-13 02:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='sent_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
