# Generated by Django 2.2 on 2019-04-09 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='end_time',
            field=models.DateTimeField(help_text='YYYY/MM/DD hh:mm'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='pref_platform',
            field=models.CharField(choices=[('online', 'Online'), ('ip', 'In-Person')], max_length=50),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_time',
            field=models.DateTimeField(help_text='YYYY/MM/DD hh:mm'),
        ),
    ]
