# Generated by Django 2.1.7 on 2019-04-07 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(limit_choices_to={'student_flag': True}, on_delete='CASCADE', related_name='student_book', to='accounts.Profile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'tutor_flag': True}, on_delete='CASCADE', related_name='tutor_book', to='accounts.Profile'),
        ),
    ]
