# Generated by Django 2.2 on 2019-04-08 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='commute_fee',
        ),
    ]
