# Generated by Django 2.2 on 2019-04-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_remove_booking_commute_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='student',
            field=models.ForeignKey(limit_choices_to={'student_flag': True}, on_delete='CASCADE', related_name='student_book', to='accounts.Profile', to_field='user'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tutor',
            field=models.ForeignKey(limit_choices_to={'tutor_flag': True}, on_delete='CASCADE', related_name='tutor_book', to='accounts.Profile', to_field='user'),
        ),
    ]
